sudo: false

language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x

before_install:
  - go get -v github.com/go-chi/chi

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)